---
name: pubnub-js-chat
version: v0.2.0
scm: github.com/pubnub/js-chat
schema: 1
files:
  - lib/dist/index.js
changelog:
  - date: 2023-10-23
    version: v0.2.0
    changes:
      - type: feature
        text: "Add moderation restriction methods."
      - type: feature
        text: "Change the way unread message count is calculated."
      - type: bug
        text: "Removing threads."
  - date: 2023-09-26
    version: v0.1.0
    changes:
      - type: feature
        text: "Initial release."
