---
name: pubnub-js-chat
version: v0.1.0
scm: github.com/pubnub/js-chat
schema: 1
files:
  - lib/dist/index.js
changelog:
  - date: 2023-09-26
    version: v0.1.0
    changes:
      - type: feature
        text: "Initial release."
  - date: 2023-09-25
    version: v0.1.0
    changes:
      - type: feature
        text: "Initial release."
