name: Jest Tests

on: [push]

jobs:
  test:
    name: Run contract tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn add --dev typescript
      - run: yarn test
