name: Jest Tests

on: [push]

jobs:
  test:
    name: Run contract tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn test --forceExit --ci --reporters=default --reporters=jest-junit
        env:
          PUBLISH_KEY: ${{ secrets.PUBLISH_KEY }}
          SUBSCRIBE_KEY: ${{ secrets.SUBSCRIBE_KEY }}
          USER_ID: ${{ secrets.USER_ID }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/junit/results.xml

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 'Test results'
          path: 'lib/test-results/junit/results.xml'
          reporter: 'jest-junit'
